### ISSUE TITLE
Integration into official actions-runner-controller

### ISSUE THREAD

**Issue by ajschmidt8** [zhaofengli/kubevirt-actions-runner#1]
Hi @zhaofengli. This is an interesting project.

Have you explored whether this could be incorporated into the official _actions-runner-controller_ project?

Some people have expressed interest in running rootless docker-in-docker in the _actions-runner-controller_ repository (e.g. [here](https://github.com/actions/actions-runner-controller/discussions/2930#discussioncomment-7123779) and [here](https://github.com/actions/actions-runner-controller/pull/2919)), but that is not officially supported.

Launching runners in VMs with rootful Docker seems like a nice alternative to trying to get rootless docker-in-docker working.

This would be especially useful to ensure parity between GitHub-hosted runners and self-hosted runners since GitHub-hosted runners use rootful Docker.

Appreciate your work here!

**Comment by ajschmidt8** [comment]
Closing due to no response.

**Comment by zhaofengli** [comment]
Sorry, somehow missed this one. This sounds like a good idea but I haven't really looked into how ARC manages the lifecycles of runners. It would be great if ARC was extended to render KubeVirt VirtualMachineInstances in addition to pods.

> This would be especially useful to ensure parity between GitHub-hosted runners and self-hosted runners since GitHub-hosted runners use rootful Docker.

Yes, this was one of the goals of the project. DinD comes with limitations and currently it's difficult to allow untrusted workflows to run privileged containers.
